/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// ADD ANY CUSTOM INTERFACES OR TYPES WITHIN THE MONGOOSE MODULE DECLARATION BELOW.
// THIS FILE WILL NOT BE CHANGED ONCE IT HAS BEEN CREATED. IF YOU NEED TO REGENERATE IT, SIMPLY DELETE IT AND RE-RUN MONGOOSE-TSGEN.

import mongoose from "mongoose";
type ObjectId = mongoose.Types.ObjectId;

declare module "mongoose" {

}
